spring.application.name=Authentication
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=mirzat
spring.datasource.password=54321
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=9090

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# key was in service class but i put hear that for clearly codeing
jwt.secret = 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b

#Default endpoint configuration
api.base-path=/v1/request

# SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mirzat5834@gmail.com
spring.mail.password=agsw sgjv ogmd oxhj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true